Fix the syntax of the Makefiles

diff --git a/openbsd/sysclean/Makefile b/openbsd/sysclean/Makefile
--- a/openbsd/sysclean/Makefile
+++ b/openbsd/sysclean/Makefile
@@ -1,11 +1,20 @@
 #	$OpenBSD$
 
-MAN=	sysclean.8
+MAN = sysclean.8
 
-SCRIPT=	sysclean.pl
+SCRIPT = sysclean.pl
 
-BINDIR?=	/usr/local/sbin
-MANDIR?=	/usr/local/man/man
+BINDIR ?= /usr/local/sbin
+MANDIR ?= /usr/local/man/man
+
+.PHONY: all clean test realinstall regress release
+
+all: realinstall
+
+clean:
+	@rm -f README.md.new || true
+
+test: regress
 
 realinstall:
 	${INSTALL} ${INSTALL_COPY} -o ${BINOWN} -g ${BINGRP} -m ${BINMODE} \
@@ -14,9 +23,9 @@ realinstall:
 README.md: sysclean.8
 	mandoc -T markdown sysclean.8 \
 	| sed	-e 's/&nbsp;/ /g' \
-		-e 's/&lt;/</g' \
-		-e 's/&gt;/>/g' \
-		-e 's/\\\[/[/g' \
+	-e 's/&lt;/</g' \
+	-e 's/&gt;/>/g' \
+	-e 's/\\\[/[/g' \
 	>$@
 
 regress: run-regress-perl-syntax \
@@ -49,26 +58,28 @@ run-regress-man-date:
 	@echo TEST: man page date
 	@if [ -d .git ]; then \
 		grep -qF -- \
-			"$$(date -r $$(git log -1 --format=%ct sysclean.8) \
-				+'.Dd %B %d, %Y')" \
-			sysclean.8 ; \
+		"$$(date -r $$(git log -1 --format=%ct sysclean.8) \
+		+'.Dd %B %d, %Y')" \
+		sysclean.8 ; \
 	elif [ -d .got ]; then \
 		grep -qF -- \
-			"$$(got log -l 1 sysclean.8 \
-				| sed -ne 's/^date: //p' \
-				| xargs -0 date -j -f '%a %b %d %T %Y %Z' \
-					+'.Dd %B %d, %Y')" \
-			sysclean.8 ; \
+		"$$(got log -l 1 sysclean.8 \
+		| sed -ne 's/^date: //p' \
+		| xargs -0 date -j -f '%a %b %d %T %Y %Z' \
+		+'.Dd %B %d, %Y')" \
+		sysclean.8 ; \
 	else \
 		echo "unchecked" ; \
 	fi
 
-.if !defined(VERSION)
-release:
-	@echo "error: please define VERSION"; false
+	.if !defined(VERSION)
+	RELEASE_CMD = @echo "error: please define VERSION"; false
+	.else
+	RELEASE_CMD = ${MAKE} sysclean-${VERSION}.tar.gz
+	.endif
 
-.else
-release: sysclean-${VERSION}.tar.gz
+release:
+	@$(RELEASE_CMD)
 
 DISTRIBUTED_FILES = \
 	Makefile \
@@ -76,11 +87,9 @@ DISTRIBUTED_FILES = \
 	sysclean.ignore \
 	${MAN} \
 	${SCRIPT}
-	
+
 sysclean-${VERSION}.tar.gz: ${DISTRIBUTED_FILES}
 	chmod a+rX ${DISTRIBUTED_FILES}
 	pax -w -zf "$@" -s ',^,sysclean-${VERSION}/,' ${DISTRIBUTED_FILES}
 
-.endif
-
-.include <bsd.prog.mk>
+	.include <bsd.prog.mk>
